Repository daniprec/ocean-route-optimization, pull requests merged in 2020-10, with the labels that each got.

#8 Funciones para extraer corrientes de los datos
  notebooks/corrientes.ipynb
  src/consumption.py
  src/stream.py
Labels: enhancement

#9 feature/review
  .gitignore
  Pipfile
  Pipfile.lock
  notebooks/velocity-functions.ipynb
  src/velocity.py
Labels: bug, enhancement

#7 Fixed velocity
  notebooks/velocity-functions.ipynb
  src/velocity.py
Labels: bug

#13 Vectorized fuel function.
  src/consumption.py
Labels: enhancement

#17 New route script
  src/route.py
  src/stream.py
  src/velocity.py
Labels: enhancement
